#!/bin/bash

# Right click
case $BLOCK_BUTTON in
    3)
    pactl set-source-mute @DEFAULT_SOURCE@ toggle
esac

pactl list sources | grep -q "Mute: yes" && [[ $? -eq 0 ]] && state="off";
case $state in
    off)
    echo "MUTE";
    exit 0;
    ;;
    *)
    echo "OPEN";
    exit 33;
    ;;
esac

exit 0;
